import Breadcrumb from "@/components/Common/Breadcrumb";
import React from "react";

const TermsOfService = () => {
  return (
    <>
      <Breadcrumb pageName="Terms of Service" description="" />
      <div className="container mx-auto px-4 py-8">
        <p className="mb-12 text-center text-sm text-gray-500">
          Last Updated: November 20, 2024
        </p>

        <div className="space-y-8 text-gray-700 dark:text-gray-300">
          <section>
            <h2 className="mb-4 text-2xl font-semibold">
              CleanFold Laundry &ndash; Terms of Service
            </h2>
            <p>
              PLEASE CAREFULLY READ THESE TERMS AND CONDITIONS OF USE BEFORE
              USING THIS SITE OR ANY OF THE SERVICES AND APPLICATIONS.
            </p>
            <p>
              The terms and conditions (&ldquo;Agreement&rdquo;) apply to
              CleanFold Laundry&apos;s (&ldquo;CFL&rdquo;) website
              (cleanfoldlaundry.com), the related mobile application and/or
              selected other domains, existing or future, content, products, and
              services (collectively, the &ldquo;Services&rdquo;). As used in
              this Agreement, &ldquo;CFL,&rdquo; &ldquo;we,&rdquo;
              &ldquo;us,&rdquo; or &ldquo;our&rdquo; shall mean CleanFold
              Laundry.
            </p>
          </section>

          <section>
            <h2 className="mb-4 text-xl font-semibold">Acceptance of Terms</h2>
            <p>
              By accessing or using our Services, whether or not you register,
              you agree to the terms of this Agreement and to the collection,
              use, and disclosure of your information as set forth in our
              Privacy Policy, which establish a contractual relationship between
              you and CFL.
            </p>
            <p>
              If you do not agree with this Agreement, please do not access or
              use our Services. As a condition to this Agreement, you
              acknowledge that we may, in our sole discretion, modify this
              Agreement at any time. All modifications will be effective
              immediately upon posting. If you continue to use the service after
              the posting of any and all modifications, it constitutes your
              consent to the changes. You are responsible for reviewing this
              Agreement from time to time so that you are aware of any and all
              changes to the Agreement.
            </p>
          </section>

          <section>
            <h2 className="mb-4 text-xl font-semibold">
              Ownership, Service Terms, and Limitations
            </h2>
            <p>
              The Services, including but not limited to, the text, content,
              photographs, images, audio, graphics, and any software (which
              includes any files or images incorporated in or generated by the
              software) available on the Services are owned and operated by CFL.
            </p>
            <p>
              The Services and related materials (“Materials”) are protected by
              copyright, trademark, domain name, trade dress, domain name,
              patent, trade secret, international treaties, and/or other
              proprietary rights and laws of the United States and other
              countries. Except as otherwise indicated in the Services and
              except for the trademarks, service marks, and trade names of other
              companies that are or may be displayed in the Services, all
              trademarks, service marks, and trade names are owned by CFL.
            </p>
          </section>

          <section>
            <h2 className="mb-4 text-xl font-semibold">
              Grant of Limited License
            </h2>
            <p>
              Subject to your compliance with the terms of the Agreement, CFL
              grants you a limited, non-exclusive, non-sub-licensable,
              revocable, non-transferrable license to: (i) access and use the
              Applications on your personal device solely in connection with
              your use of the Services; and (ii) access and use any content,
              information, and related Materials that may be made available
              through the Services, in each case solely for your personal,
              noncommercial use. Any rights not expressly granted herein are
              reserved by CFL and CFL’s licensors.
            </p>
          </section>

          <section>
            <h2 className="mb-4 text-xl font-semibold">
              User Requirements and Conduct
            </h2>
            <p>
              In order to use most aspects of the Services, you must register
              for and maintain an active personal user Services account
              (“Account”). You must be at least 13 years of age to obtain an
              Account. Account registration requires you to submit to CFL
              certain personal information, such as your name, address, and
              mobile phone number, as well as at least one valid credit card.
            </p>
          </section>

          <section>
            <h2 className="mb-4 text-xl font-semibold">
              Damaged or Lost Items
            </h2>
            <p>
              We exercise utmost care in cleaning and processing garments
              entrusted to us and use such processes, which, in our opinion, are
              best suited to the nature and conditions of each individual
              garment. Nevertheless, we cannot assume responsibility for
              inherent weaknesses or defects in materials which may result in
              tears or development of small holes in fabric that are not readily
              apparent prior to processing.
            </p>
          </section>

          <section>
            <h2 className="mb-4 text-xl font-semibold">Disclaimer</h2>
            <p>
              THE MATERIALS AND THE SERVICES ARE PROVIDED &ldquo;AS IS&rdquo;
              AND WITHOUT WARRANTIES OF ANY KIND EITHER EXPRESS OR IMPLIED. TO
              THE FULLEST EXTENT PERMISSIBLE PURSUANT TO APPLICABLE LAW, CFL AND
              ITS OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, OR REPRESENTATIVES
              DISCLAIM WITH RESPECT TO THE SERVICES AND THE MATERIALS HEREIN ALL
              WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO,
              IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
              PURPOSE.
            </p>
          </section>

          <section>
            <h2 className="mb-4 text-xl font-semibold">
              Limitation of Liability
            </h2>
            <p>
              UNDER NO CIRCUMSTANCES, INCLUDING, BUT NOT LIMITED TO, NEGLIGENCE,
              SHALL CFL OR ITS OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, OR
              REPRESENTATIVES BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY
              SPECIAL, CONSEQUENTIAL, INCIDENTAL, DIRECT, INDIRECT, OR PUNITIVE
              DAMAGES OR ANY OTHER LOSS OR INJURY THAT RESULT FROM THE USE OF,
              OR THE INABILITY TO USE, THE SERVICES OR THE MATERIALS.
            </p>
          </section>

          <section>
            <h2 className="mb-4 text-xl font-semibold">Contact Us</h2>
            <p>
              If you have any questions about these Terms of Service, please
              contact us at{" "}
              <a
                href="mailto:CleanFoldLaundryUSA@gmail.com"
                className="text-blue-500 hover:underline"
              >
                CleanFoldLaundryUSA@gmail.com
              </a>
              .
            </p>
          </section>
        </div>
      </div>
    </>
  );
};

export default TermsOfService;
